services:
  laravel.test:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - './src:/var/www/html'
    depends_on:
      - mysql
    networks:
      - sail

  mysql:
    image: mysql:8.4
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    volumes:
      - sail-mysql:/var/lib/mysql
    networks:
      - sail

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: sail
      PMA_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - sail

networks:
  sail:

volumes:
  sail-mysql: